[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pythonodejs"
dynamic = ["version"]
description = "Python-NodeJS interop library"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "0880" }]

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
fallback_version = "0.0.1"
version_file = "src/pythonodejs/_version.py"

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-*"
skip = "*-musllinux_*"

test-requires = ["pytest"]
test-command = "pytest -v -s --tb=long {project}/tests"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.windows]
archs = ["AMD64"]

[project.urls]
Homepage = "https://github.com/0880880/pythonodejs"
Repository = "https://github.com/0880880/pythonodejs"
Issues = "https://github.com/0880880/pythonodejs/issues"
