class NodeJS:
    def __init__(self, path: str, thread_pool_size: int = 4): ...
    def __repr__(self): ...
    def eval_cjs(self, code: str) -> any: ...
    def require_cjs(self, url: str) -> any: ...
    async def import_esm(self, url: str) -> any: ...
