name: Build wheels

on:
  push:
    branches: [ main, rewrite-cpython ]
  pull_request:

jobs:
  build-manylinux:
    name: Build Linux wheels (manylinux via cibuildwheel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-
      - name: Install deps & Setup
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev curl pkg-config autoconf libtool automake \
                    ccache mold ninja-build clang-21 \
                    gcc g++ make gawk m4 texinfo bison \
                    python3 wget xz-utils gdb sed 
          sudo apt install linux-headers-$(uname -r)
          export LDFLAGS="-fuse-ld=mold"
          export LD=/usr/bin/mold
      - name: Build GLIBC 2.28
        run: |
          export CC="gcc"
          export CXX="g++"
          cd /tmp
          wget https://ftp.gnu.org/gnu/libc/glibc-2.28.tar.xz
          tar -xf glibc-2.28.tar.xz
          cd glibc-2.28
          mkdir build && cd build
          ../configure --prefix=/opt/glibc-2.28 --disable-werror
          make -j$(nproc)

      - name: Build libnode
        run: |
          export CC="ccache clang"
          export CXX="ccache clang++"
          cd include/node
          ./configure --ninja --shared
          make -j$(nproc)
      - name: Create archive
        run: |
          cd include/node/out/Release/lib
          ln -s $(ls -v libnode.so.* | tail -n 1) libnode.so
          tar -cJf "libnode-linux.tar.xz" libnode.*
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libnode-windows
          path: include/node/out/Release/lib/*.tar.xz

  build-macos:
    name: Build macOS wheels
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Homebrew deps
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
          brew update || true
          brew install python3 cmake pkg-config ninja ccache || true
      - name: Build libnode
        run: |
          cd include/node
          ./configure --ninja --shared
          make
      - name: Create archive
        run: |
          cd include/node/out/Release
          ln -s $(ls -v libnode.* | tail -n 1) libnode.dylib
          tar -cJf "libnode-macos.tar.xz" libnode.*
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libnode-windows
          path: include/node/out/Release/lib/*.tar.xz


  build-windows:
    name: Build Windows wheels
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install build tools
        shell: pwsh
        run: |
          choco install -y python visualstudio2022buildtools curl nasm 7zip
          choco install -y visualstudio2022-workload-nodebuildtools
          $progressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          winget configure ./include/node/.configurations/configuration.dsc.yaml --accept-configuration-agreements --disable-interactivity
      - name: Build libnode (Windows host - MSVC)
        run: |
          cd include\node
          .\vcbuild.bat x64 dll openssl-no-asm
      - name: Create archive
        run: |
          cd include\node\out\Release
          7z a -mx9 "libnode-windows.zip" libnode.*
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libnode-windows
          path: include/node/out/Release/*.zip

